data_url: "https://raw.githubusercontent.com/renjith-digicat/random_file_shares/main/HousingData.csv"   # URL from where we can download the data


data_split:
  raw_data_save_path: "./artefacts/raw_data.csv"    # the filename for raw downloaded data
  cleansed_data_save_path: "./artefacts/cleansed_data.csv"    # the filename for cleansed data
  train_data_save_path: "./artefacts/train_data.csv"  # save path of the train split of the data - used for training the model
  test_data_save_path: "./artefacts/test_data.csv"   # save path of the test split of the data - used for testing the trained models performance
  val_data_save_path: "./artefacts/val_data.csv"   # save path of the validation split of the data - used for hyperparameter tuning
  seed: 42    # set a seed for random data split
  test_frac: 0.2   # the fraction of data kept for testing - "train_and_val_frac = 1 - test_frac"
  val_frac: 0.2   # the fraction of data from the remaining 1-test_frac that should be kept for validation, the rest will be used for training
  label_col: "price"   # column name of the predictor variable - used for splitting data in a proportionate way
  categorical_cols: [ "mainroad", "guestroom", "basement", "hotwaterheating",  # categorical column names in the input data
                      "airconditioning", "prefarea", "furnishingstatus" ]
  numeric_cols: [ "area", "bedrooms", "bathrooms", "stories", "parking" ]   # numerical column names in the input data

DVC_REMOTE: "/Users/rbaby/Code/mlops/dvc"
DVC_REMOTE_NAME: "test_remote"